//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccessData.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLEADO
    {
        public int ID { get; set; }
        public string NOMBRE { get; set; }
        public string PRIMERAPELLIDO { get; set; }
        public string SEGUNDOAPELLIDO { get; set; }
        public System.DateTime FECHAINGRESO { get; set; }
        public int EDAD { get; set; }
        public Nullable<decimal> SALARIO { get; set; }
        public int IDCARGO { get; set; }
        public int IDCIUDAD { get; set; }
    
        public virtual CARGO CARGO { get; set; }
        public virtual CIUDAD CIUDAD { get; set; }
    }
}
